name: Build and Publish

on: 
  push:
    tags:
      - '*'

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest      

    permissions:
      contents: write                         

    env:
      Solution_Name: StravaUploader.sln
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build .\src\${{ env.Solution_Name }} -c Release /property:Version=${{github.ref_name}}

    - name: dotnet publish
      run: dotnet publish .\src\${{ env.Solution_Name }} -c Release -o pub /property:Version=${{github.ref_name}}

    - name: Make release notes
      run: git log --pretty='format:- %s' $(git describe --tags --abbrev=0 @^)..@ > notes.md

    - name: Create Release
      uses: ncipollo/release-action@v1.10.0
      with:
        artifacts: "pub/StravaUploader.exe,pub/appsettings.json"
        bodyFile: "notes.md"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{github.ref_name}}
